GET http://localhost:3000/products/


###
GET http://localhost:3000/products/2

###
POST http://localhost:3000/products/
content-type: application/json

{
  "input_name": "Rainer",
  "input_price": 4,
  "input_url": "https://unsplash.com/photos/3ORoQEJY9LA",
  "input_description": "nice cheap great lager"
}


###
DELETE http://localhost:3000/products/18


###
PATCH http://localhost:3000/products/15
content-type: application/json

{
  "new_name": "Rainier"
 
}

###
PATCH http://localhost:3000/products/5
content-type: application/json

{
  "new_name": "Ninkasi",
  "new_price": 8,
  "new_url": "beer.com",
  "new_description": "great hoppy dark ipa"
}