
#index
GET http://localhost:3000/products.json


#show
###
GET http://localhost:3000/products/3.json

#create
###
POST http://localhost:3000/products.json
content-type: application/json

{
  "input_name": "Corona",
  "input_price": 2,
  "input_description": "mexican american style lager",
  "input_inventory" : 99,
  "input_images" : [
    "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.pKnPQFE7c__WtDWh18ml1wAAAA%26pid%3DApi&f=1", "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.ZQf2rHaVae8Aa_GpnndGCAEsCo%26pid%3DApi&f=1"
  ]
}

#delete
###
DELETE http://localhost:3000/products/23.json


#update
###
PATCH http://localhost:3000/products/15.json
content-type: application/json

{
  "new_name": "Rainier",
  "new_price": 3
 
}

#update
###
PATCH http://localhost:3000/products/5.json
content-type: application/json

{
  "new_name": "Ninkasi",
  "new_price": 8,
  "new_url": "beer.com",
  "new_description": "great hoppy dark ipa"
}

####-_------------------------Suppliers__________----------------__----__---_---__----

#index
GET http://localhost:3000/suppliers.json

#show
###
GET http://localhost:3000/suppliers/3.json

#_________________________________________

#images
###
POST http://localhost:3000/images.json
content-type: application/json

{
  "url": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.SI2IZDEwxJLK1S2l_GkFUwHaHa%26pid%3DApi&f=1",

  "product_id": 7
}

#------------------USERS--------------------------------
#users create
###
POST http://localhost:3000/users.json 
content-type: application/json

{
  "name": "derek",
  "email": "derek@email.com",
  "password": "password",
  "password_confirmation":"password"
}

#sessions
###
POST http://localhost:3000/sessions 
content-type: application/json

{
  "email": "bob@email.com",
  "password": "password"
}



