
#index
GET http://localhost:3000/products.json


#show
###
GET http://localhost:3000/products/2.json

#create
###
POST http://localhost:3000/products.json
content-type: application/json

{
  "input_name": "Rainer",
  "input_price": 4,
  "input_url": "https://unsplash.com/photos/3ORoQEJY9LA",
  "input_description": "nice cheap great lager"
}

#delete
###
DELETE http://localhost:3000/products/8.json


#update not working
###
PATCH http://localhost:3000/products/15.json
content-type: application/json

{
  "new_name": "Rainier"
 
}

#update
###
PATCH http://localhost:3000/products/5
content-type: application/json

{
  "new_name": "Ninkasi",
  "new_price": 8,
  "new_url": "beer.com",
  "new_description": "great hoppy dark ipa"
}